name: Deploy Django to VM

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        env:
        run: |
          python manage.py test



  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to web_server_01
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST_1 }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "scholarly" ]; then
              cd scholarly
              git pull origin main
              sudo apt-get install -y python3.8-venv
              python3 -m venv venv
              source venv/bin/activate
              sudo systemctl restart scholarly.service
            else
              git clone https://github.com/mojalefakodisang/scholarly
              cd scholarly
              sudo apt-get install -y python3.8-venv
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              sudo systemctl restart scholarly.service
            fi

      - name: Deploy to web_server_02
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST_2 }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "scholarly" ]; then
              cd scholarly
              git pull origin main
              sudo apt-get install -y python3.8-venv
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              sudo systemctl restart scholarly.service
            else
              git clone https://github.com/mojalefakodisang/scholarly
              cd scholarly
              sudo apt-get install -y python3.8-venv
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              sudo systemctl restart scholarly.service
            fi
