name: Deploy Django to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
          - name: Set up environment variables
          env:
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            
      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "scholarly" ]; then
            cd scholarly
            git pull origin main
            sudo apt-get install -y python3-pip
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              systemctl restart scholarly.service
            else
              git clone https://github.com/mojalefakodisang/scholarly
              cd scholarly
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              systemctl restart scholarly.service
            fi
